"""add foreign keys and relationships

Revision ID: 35b11725006b
Revises: dcb5dcca565b
Create Date: 2026-02-20 01:51:49.733884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35b11725006b'
down_revision: Union[str, Sequence[str], None] = 'dcb5dcca565b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge_versions', 'description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('challenge_versions', 'objectives',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('challenge_versions', 'scoring_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('challenge_versions', 'hints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('challenge_versions', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.drop_constraint(op.f('challenge_versions_challenge_id_fkey'), 'challenge_versions', type_='foreignkey')
    op.create_foreign_key(None, 'challenge_versions', 'challenges', ['challenge_id'], ['id'], ondelete='CASCADE')
    op.alter_column('objective_results', 'objective_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('objective_results', 'points_awarded',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(op.f('objective_results_submission_id_fkey'), 'objective_results', type_='foreignkey')
    op.create_foreign_key(None, 'objective_results', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.alter_column('submissions', 'score_awarded',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(op.f('submissions_user_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_challenge_version_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'challenge_versions', ['challenge_version_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_skill_progress', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(op.f('user_skill_progress_skill_id_fkey'), 'user_skill_progress', type_='foreignkey')
    op.drop_constraint(op.f('user_skill_progress_user_id_fkey'), 'user_skill_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_skill_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_skill_progress', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skill_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_skill_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_skill_progress_user_id_fkey'), 'user_skill_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_skill_progress_skill_id_fkey'), 'user_skill_progress', 'skills', ['skill_id'], ['id'])
    op.alter_column('user_skill_progress', 'score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_challenge_version_id_fkey'), 'submissions', 'challenge_versions', ['challenge_version_id'], ['id'])
    op.create_foreign_key(op.f('submissions_user_id_fkey'), 'submissions', 'users', ['user_id'], ['id'])
    op.alter_column('submissions', 'score_awarded',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'objective_results', type_='foreignkey')
    op.create_foreign_key(op.f('objective_results_submission_id_fkey'), 'objective_results', 'submissions', ['submission_id'], ['id'])
    op.alter_column('objective_results', 'points_awarded',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('objective_results', 'objective_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'challenge_versions', type_='foreignkey')
    op.create_foreign_key(op.f('challenge_versions_challenge_id_fkey'), 'challenge_versions', 'challenges', ['challenge_id'], ['id'])
    op.alter_column('challenge_versions', 'skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('challenge_versions', 'hints',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('challenge_versions', 'scoring_rules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('challenge_versions', 'objectives',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('challenge_versions', 'description',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
