"""add tenant_id to submissions

Revision ID: bd20b49d2256
Revises: f618a080fd34
Create Date: 2026-03-04 23:18:06.169817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd20b49d2256'
down_revision: Union[str, Sequence[str], None] = 'f618a080fd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('tenant_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'tenant_id')
    # ### end Alembic commands ###
