"""add level to user_skill_progress

Revision ID: f618a080fd34
Revises: 122fb0241f73
Create Date: 2026-02-26 22:53:41.070767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f618a080fd34'
down_revision: Union[str, Sequence[str], None] = '122fb0241f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skill_progress', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skill_progress', 'level')
    # ### end Alembic commands ###
